name: "Code Review Assistant - SCSS"

on:
    pull_request:
        branches:
            - "develop"
        paths:
            - "**.scss"

jobs:
    CRAd1acb3b4-1dcd-4995-b8e5-0ac3905fd2cf:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v1"
              with:
                  fetch-depth: 1              

            - name: "Setup NodeJS"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "12.x"

            - name: "Cache node_modules"
              uses: "actions/cache@v1"
              id: "cache"
              with:
                  path: "node_modules"
                  key: ${{ runner.os }}-cache-${{ hashFiles('yarn.lock') }}

            - run: "yarn install"
              if: "steps.cache.outputs.cache-hit != 'true'"

            - run: "yarn run lint:scss --annotations-type=GITHUB_ACTIONS"