name: "Code Review Assistant - ISML"

on:
    pull_request:
        branches:
            - "develop"
        paths:
            - "**.isml"

jobs:
    CRA4d88ab4e-6f31-4676-9796-315cd5c57779:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v1"

            - name: "Setup NodeJS"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "12.x"

            - name: "Cache node_modules"
              uses: "actions/cache@v1"
              id: "cache"
              with:
                  path: "node_modules"
                  key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}

            - run: "yarn install"
              if: "steps.cache.outputs.cache-hit != 'true'"

            - run: "yarn run lint:isml --annotations-type=GITHUB_ACTIONS"