name: "Code Review Assistant - JS"

on:
    pull_request:
        branches:
            - "develop"
        paths:
            - "**.js"

jobs:
    CRA99d31b65-5d66-41b1-9ebf-b226c3b9d67c:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v1"
              with:
                  fetch-depth: 1

            - name: "Setup NodeJS"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "12.x"

            - name: "Cache node_modules"
              uses: "actions/cache@v1"
              id: "cache"
              with:
                  path: "node_modules"
                  key: ${{ runner.os }}-cache-${{ hashFiles('yarn.lock') }}

            - run: "yarn install"
              if: "steps.cache.outputs.cache-hit != 'true'"

            - run: "yarn run lint:js --annotations-type=GITHUB_ACTIONS"